# Javascript Node CircleCI 2.1 configuration file
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.1
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
    
      - run:
          name: Configure aws
          command: aws configure


  build_package:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    steps:
      - checkout

      # SETUP
      - run:
          name: Say Hello
          command: echo "Hello Surfy App !"
      - run:
          name: Install  Node.js 16.13.0 with build in nvm tool
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v16.13.0 && nvm use v16.13.0 && nvm alias default v16.13.0
      - run:
          name: Check node version
          command: node -v 
    
     # BUILD
      - run:
          name: Install dev dependancies
          command: yarn install

      # PUSH IMAGE TO AWS (ECR)
      - run:
          name: Setup AWS CLI
          command: sudo apt-get update && sudo apt-get install awscli

      - run:
          name: Login to docker (ECR)
          command: aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 163668745705.dkr.ecr.eu-west-3.amazonaws.com

workflows:
  deploy-surfy:
    jobs:
      - build_package:
          filters:
            branches:
              only:
                - main
      - aws-cli-cred-setup:
          context: aws