# Javascript Node CircleCI 2.1 configuration file
version: 2.1
jobs:
  mytest:
    steps:
      # SETUP
      - run:
          name: Say Hello
          command: /bin/bash echo "Hello"
workflows:
  build-deploy:
    jobs:
      - mytest:
          filters:
            branches:
              only:
                - main