# Javascript Node CircleCI 2.1 configuration file
version: 2.1
jobs:
  mytest:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    steps:
      # SETUP
      - run:
          name: Say Hello
          command: /bin/bash echo "Hello"

workflows:
  build-deploy:
    jobs:
      - mytest:
          filters:
            branches:
              only:
                - main