# Javascript Node CircleCI 2.1 configuration file
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.1
jobs:
  build_package:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    steps:
      - checkout

      # SETUP
      - run:
          name: Say Hello
          command: echo "Hello Surfy App !"
      - run:
          name: Install  Node.js 16.13.0 with build in nvm tool
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v16.13.0 && nvm use v16.13.0 && nvm alias default v16.13.0
      - run:
          name: Check node version
          command: node -v 
    
     # BUILD
      - run:
          name: Install dev dependancies
          command: yarn install

      # PUSH IMAGE TO AWS (ECR)
      - run:
          name: Setup AWS CLI
          command: sudo apt-get update && sudo apt-get install awscli

      - run:
          name: Login to docker (ECR)
          command: aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 163668745705.dkr.ecr.eu-west-3.amazonaws.com

      - run:
          name: Build docker image
          command: docker build -t surfy .

      - run:
          name: Tag docker image
          command: docker tag surfy:latest 163668745705.dkr.ecr.eu-west-3.amazonaws.com/surfy-frontend:latest

      - run:
          name: Push docker image to registry (ECR)
          command: docker push 163668745705.dkr.ecr.eu-west-3.amazonaws.com/surfy-frontend:latest

deploy_aws_production:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          name: Deploy new image to ECS
          command: aws ecs update-service --cluster arn:aws:ecs:eu-west-3:163668745705:cluster/my-cluster --service arn:aws:ecs:eu-west-3:163668745705:task/my-cluster/ef3c80e8dd3848968c911b8a04e229be --force-new-deployment


workflows:
  deploy-surfy:
    jobs:
      - build_package:
          filters:
            branches:
              only:
                - main            
      - deploy_aws_production:
          context: aws
          requires:
            - build_package
 